//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RigReading
    {
        public long RowId { get; set; }
        public int Rig { get; set; }
        public string MinerDescription { get; set; }
        public Nullable<int> Elapsed { get; set; }
        public Nullable<double> AverageMH { get; set; }
        public Nullable<int> GetWorks { get; set; }
        public Nullable<int> Accepted { get; set; }
        public Nullable<int> Rejected { get; set; }
        public Nullable<int> HardwareErrors { get; set; }
        public Nullable<double> Utility { get; set; }
        public Nullable<int> Discarded { get; set; }
        public Nullable<int> Stale { get; set; }
        public Nullable<int> GetFailures { get; set; }
        public Nullable<int> LoaclWork { get; set; }
        public Nullable<int> RemoteFailures { get; set; }
        public Nullable<int> NetworkBlocks { get; set; }
        public Nullable<double> TotalMH { get; set; }
        public Nullable<double> WorkUtility { get; set; }
        public Nullable<double> DifficultyAccepted { get; set; }
        public Nullable<double> DifficultyRejected { get; set; }
        public Nullable<double> DifficultyStale { get; set; }
        public Nullable<long> BestShare { get; set; }
        public Nullable<double> DeviceHardware { get; set; }
        public Nullable<double> DeviceRejected { get; set; }
        public Nullable<double> PoolRejected { get; set; }
        public Nullable<double> PoolStale { get; set; }
        public Nullable<System.DateTime> CollectedOn { get; set; }
        public Nullable<bool> IsError { get; set; }
        public Nullable<double> CurrentMH { get; set; }
    }
}
