//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDataAcess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long RowId { get; set; }
        public string TxId { get; set; }
        public double Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
    }
}
